name: Build Windows

on:
  workflow_dispatch

jobs:
  create_release:
    if: contains('["raub"]', github.actor)
    runs-on: ubuntu-latest

    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}

    steps:

      - name: Fetch Repository
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.12.1
          cache: 'npm'

      - name: Get Npm Version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@master

      - name: Create Draft Release
        id: create_release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          draft: true
          tag_name: ${{ steps.package-version.outputs.current-version }}
          name: Release ${{ steps.package-version.outputs.current-version }}
          body: Update ${{ steps.package-version.outputs.current-version }}

  build:
    strategy:
        matrix:
          os: [ubuntu-20.04, windows-2022, macos-11, [self-hosted, linux, ARM64]]

    runs-on: ${{ matrix.os }}

    steps:

      - name: Fetch Repository
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.12.1
          cache: 'npm'

      - name: Get Npm Version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@master

      - name: Install Modules
        run: npm ci --ignore-scripts

      - name: Build Current Binary
        run: npm run build-all

      - name: Zip the binaries
        id: zip-files
        run: node zip >> $GITHUB_OUTPUT

      - name: Store Binaries
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          draft: true
          tag_name: ${{ steps.package-version.outputs.current-version }}
          name: Release ${{ steps.package-version.outputs.current-version }}
          files: ${{ steps.zip-files.outputs.zip }}
