name: Build Aarch64

on:
  workflow_dispatch

jobs:
  Build:
    if: contains('["raub"]', github.actor)
    runs-on: [self-hosted, linux, ARM64]

    steps:

      - name: Fetch Repository
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.12.1
          cache: 'npm'

      - name: Install Modules
        run: npm ci

      - name: Run Build
        run: npm run build-all

      - name: Store Binaries
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          draft: true
          tag_name: linux-${{ github.run }}-${{ github.sha }}
          name: Aarch64
          body: Aarch64 binaries at ${{ github.sha }}
          files: bin-aarch64/segfault.node
