name: Build All

on:
  workflow_dispatch

jobs:
  create_release:
    name: Create Release
    if: contains('["raub"]', github.actor)
    runs-on: ubuntu-latest

    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}

    steps:

      - name: Fetch Repository
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.12.1
          cache: 'npm'

      - name: Get Package Version
        id: package-version
        run: node action-version >> $GITHUB_OUTPUT

      - name: Create Draft Release
        id: create_release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          draft: true
          tag_name: ${{ steps.package-version.outputs.version }}
          name: Release ${{ steps.package-version.outputs.version }}
          body: Binaries at ${{ github.sha }}

  build:
    name: Build
    strategy:
        matrix:
          os: [ubuntu-20.04, windows-2022, macos-11, [self-hosted, linux, ARM64]]

    runs-on: ${{ matrix.os }}

    steps:

      - name: Fetch Repository
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.12.1
          cache: 'npm'

      - name: Install Modules
        run: npm ci --ignore-scripts

      - name: Build Current Binary
        run: npm run build-all

      - name: Get Package Version
        id: package-version
        run: node action-version >> $GITHUB_OUTPUT

      - name: Zip Files
        id: zip-files
        run: node action-zip >> $GITHUB_OUTPUT

      - name: Zip Files ls
        run: ls

      - name: echo ver
        run: echo "ver ${{ steps.package-version.outputs.version }}"

      - name: echo zip
        run: echo "zip ${{ steps.zip-files.outputs.zip }}"

      - name: Store Binaries
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          draft: true
          tag_name: ${{ steps.package-version.outputs.version }}
          name: Release ${{ steps.package-version.outputs.version }}
          files: ${{ steps.zip-files.outputs.zip }}
